#+title: Self-Improvement Advises from 4Chan
#+startup: content

#+begin_quote
| ~󰎚~

This content was transcribed from the images present on a 4Chan curated pack.

*Enjoy in being a better version of yourself!*
#+end_quote

* 10 Personal Finances Tips
# Sun Jan 21 04:50:16 2024
1. Spend less than you earn.
2. Build multiple streams of income.
3. Pay down the highest interest bearing debt first.
4. Income does not determine wealth.
5. Do everything in moderation.
6. Know the difference between good debt and bad debt.
7. Develop a Workable Household Budget.
8. Track your income and expenses.
9. Never assume past performance guarantees future results.
10. Pay the bills on time. By doing so you'll avoid spending money on needless late fees.
* The 3 Types of People To Surround Yourself With
- *The Dreamer:* It’s important to have someone who always thinks positive and keeps you believing!
- *The Hardworker:* You need someone who will keep pushing your work ethic to new heights into actions
- *The Realist:* This person will keep you level-headed and make sure your thinking deeper ...
* 5 LEARNABLE MINDSETS OF SUCCESSFUL PEOPLE
1. Successful people know and accept themselves.
2. Successful people set goals congruent with their personality, values, interests, strengths, skills, mission and purpose.
3. Successful people know they have much more control over the trajectory of their lives than others realize.
4. Successful people accept that they will repeatedly go through tough times.
5. Successful people know that once they get to their destination, they will find another.
* 9 THINGS TO DO IN YOUR 20S TO BECOME A MILLIONAIRE BY 30
1. Focus on earning.
2. Develop multiple streams of income
3. Save to invest, don't save to save.
4. Don't show off - show up.
5. Change your mindset about money.
6. Invest in yourself.
7. Set goals and visualize achieving them.
8. Start hanging out with people you admire.
9. Shoot for $10 million, not $1 million.
* tips_for_a_successful_life
*Millionaire's rules you will never learn in school*
- *You will not make six figure salary after school:* You will have to work hard for what you get
- *Your parents know something you don't:* Perhaps, before you were born, your parents weren't as boring as they are now
- *Life is not fair. Get used to It:* Stop expecting life to hand you the things you think you "deserve"
- *"Flipping Burgers" is not beneath your dignity:* Swallow your pride and take that job you think is beneath you as stepping stone
- *Your school may have done away with winners and losers but life has not:* The result of an exam does not justify the means. It doesn't bear the slightest resemblance to anything in real life
- *The world doesn't care about your self esteem*
- *If you mess up, it's not your parents fault:* Stop spreading the blame around and take responsibility for your failures
- *Life is not divided into semesters:* Once life starts, it just goes on and on. So spend your time doing something worthwhile
* WHY BECOMING RICH QUICK IS DANGEROUS
Did you know that many lottery winners go broke after a couple of years?
1. If you don’t work your ass off for your money you will not understand the real value of it
2. Money that comes fast gets spent fast
3. Many people who get rich quick or by luck stop spending it logically and start spending emotionally
4. You need a certain financial education in order to invest your money in a correct and clever way
5. Remember that you can always fall way faster than you climbed to the top

Being broke can teach you the most valuable lessons in life which spoiled rich kids will never understand.
That’s why I’m grateful for the fact that I failed so badly before I started making real money.
* great_minds_discuss_ideas
- *Great minds discuss ideas:* philosophy science happiness epistomology psychology art creativity knowledge self spirituality improvement solutions abstraction music relationships peace
- *Average minds discuss events:* news weather politics religion television sales sports work concerts activities plans
- *Small minds discuss people:* gossip drama politicians peers clergymen leaders neighbors friends family coworkers
* Invest in yourself
- Quit a habit
- Work out
- Meditate
- Self-reflect
- Learn a new skill
- Read
* LACK PEOPLE WITH DREAMS
#+begin_quote
The worst people to serve are the Poor people.

- Give them free, they think it's a trap.
- Tell them it's a small investment, they'll say can't earn much.
- Tell them to come in big, they'll say no money.
- Tell them try new things, they'll say no experience.
- Tell them it's traditional business, hard to do.
- Tell them it's a new business model, they'll say it's MLM.
- Tell them to run a shop, they'll say no freedom.
- Tell them run new business, They'll say no expertise.

They do have somethings in common: They love to ask google, listen to friends who are as hopeless as them, they think more than an university professor and do less than a blind man. Just ask them, what can they do.
They won't be able to answer you.

My conclusion:
- Instead of your heart beats faster, why not you just act faster a bit;
- Instead of just thinking about it, why not do something about it.
Poor people fail because on one common behavior: *Their Whole Life is About Waiting.*
#+end_quote
*WE ARE NEVER IN LACK OF MONEY.*\\
*WE LACK PEOPLE WITH DREAMS,*\\
*WHO CAN DIE FOR THOSE DREAMS.*
* RICH POOR VS POOR PEOPLE
- *Rich people*: Would rather be educated than entertained.
- *Poor people*: Would rather be entertained than educated.
* Right environment
*Your environment matters*

A TREE has to be planted in the right Environment in order to Grow or else it will DIE

A human being has the choice and power to move from.

From the Wrong Environment to the RIGHT one.

In order to grow...
* Spend your time wisely
*Everyday you get:* 24 hours 1,440 minutes 86,400 seconds

=Nonrefundable. Nonrenewable.=

*Be very selective of how you use your time.*
- Spending: Non-educational TV, Going out excessively, Too much social media, Gossiping about others
- Investing: Networking, Learn a new skill, Read a new book, Building a side hustle
* Successful vs Unsuccessful People
** SUCCESSFUL PEOPLE
1. Read every day
2. Compliment
3. Embrace Change
4. Forgive others
5. Talk about ideas
6. Continuously learn
7. Accept responsibility for their failures
** UNSUCCESSFUL PEOPLE
1. Watch TV every day
2. Criticize
3. Fear change
4. Hold a grudge
5. Talk about people
6. Think they know it all
7. Blame others for their failures
* Surround yourself with good people
Surround yourself with people that push you to do better.

No drama or negativity.

Just higher goals and higher motivation.

Good times and positive energy.

No jealousy or hate.

Simply bringing out the absolute best in each other.
* Successful vs Unsuccessful People
** SUCCESSFUL PEOPLE
1. Give other people credit for their victories
2. Exude joy
3. Share information and data
4. Continuously learn
5. Keep a journal
6. Keep a "TO-DO Project" list
7. Talk about ideas
8. Set goals and develop life plans
9. Want others to succeed
10. Operate from a transformational perspective
11. Accept responsibility
12. Read everyday
13. Keep a "TO-*BE*" list
14. Forgive others
15. Embrace change
16. Compliment
** UNSUCCESSFUL PEOPLE
1. Secretely hope others to fail
2. Don't know what they want to be
3. Blame others for their failures
4. Hold a grudge
5. Talk about people
6. Fly by their seats or their pants
7. Take all credits of their victories
8. Operate from a transactional perspective
9. Exude anger
10. Horde information and data
11. Say they keep a journal but they don't
12. Think they know it all
13. Fear change
14. Criticize
15. Have a sense of entitlement
16. Never set goals
* Little chickens
Most People are poor because, when it comes to investing, the world is filled with Chickens Littles running around yelling, "The sky is falling! The sky is falling!" And Chickens Littles are effective, because everyone of us is a little chicken.\\
It often takes great Courage to not let rumors and talk of doom and gloom affect your doubts and fears.\\
But a savvy investor knows that the seemingly worst of times is actually the best of times to make money.\\
When everyone else is too afraid to act, they pull the trigger and are rewarded.
* Make money: The startup way
1. *Find a product* (or a idea) that is popular but not perfect.
2. Buy one and *study* it in detail
3. Figure out how to *improve*
4. Make a *prototype*
5. *Show* the prototype o 100 people
6. *Remake it*, until people start ordering it (ex. Kickstarter)
7. Find a *co-founder* who can build it with you
8. *Split* with your co-founder 50% (use vesting)
9. Find a person with a lot of money, an *investor*
10. *Give* her 10% of your company
11. *Make* the product
12. *Sell your product* to 1 million people
13. Get *more money*
14. List your company on *stock exchange* like NASDAQ
15. Your investor, your co-founder and you all make money when you *sell shares* there
* You need 3 hobbies
# Sun Jan 21 05:58:38 2024
- One to keep you *creative*
- One to keep you *in shape*
- One to make you *money*
* 10 simple rules for self-improvement
- Find the right circle
- Educate yourself daily
- Get comfortable being uncomfortable
- Avoid negative people
- Take up a new life challenge
- Write down your goals
- Wake up early
- Improve upon your strengths
- Ask for feedback
- Acklowledge your flaws
* 10 things that require zero talent
- Being on time
- Work ethic
- Effort
- Body language
- Energy
- Attitude
- Passion
- Being coachable
- Doing extra
- Being prepared
* 19 Habits to live by
- Network.
- Dream big.
- Plan ahead.
- Get up early.
- Stay focused.
- Watch less TV.
- Read more books.
- Invest in yourself.
- Avoid time wasters.
- Take calculated risks.
- Write down your goals.
- Live on less than you make.
- Make your health a priority.
- Do work that matters to you.
- Learn from people you admire.
- Foster meaningful relationships.
- Take action, even when it's scary.
- Cultivate an attitude of gratitude.
- Have a powerful and inspiring "why".
* Three simple rules in life
1. If you do not *go* after what you want, you'll never have it.
2. If you do not *ask* the answer will always be *no*.
3. If you do not step *forward*, you *always* be in the same place
* 4 Ways to invest your time wisely
1. Turn off television.
  - Try educational YouTube videos instead.
2. Read more books
  - Aim for 30 minutes per day of uninterrupted reading.
3. Listen to podcasts.
  - Try replacing music with a podcast during your commute.
4. Plan your day the night before.
  - Use a journal to structure your goals throughout the day
* Adopt the mindset
You choose how you experience life. You can't choose the cards you were dealt but you choose what to do with them.

STOP VIEWING YOURSELF AS A VICTIM\\
"Avenger" and "Survivor" self-images presuppose victimhood.

BE TRULY INDEPENDENT

** Practice Mindfulness Meditation
You can't just resolve to think in a new way.\\
You have a million more or less conscious narratives in your head that influence everything. Work to get rid of them. Learn to be objective and control your emotions.

Being more mindful is also the pre-requisite for any following advice.

RESEARCH THE PRATICE, put the work in, don't expect an instasnt fix.
** Stay In The Present Moment
Stop fantasizing about the future. Stop dreading it.\\
Stop wallowing in the past mistakes. Stop thinking how much better things used to be.

Think objectively what you want from the future, and non-judgmentally learn from past.
** Set Goals
Look at yourself and objectively decite what you CAN improve upon first.

DO NOT think about what you "should" improve upon first. If you're spending months or years thinking "I need to do X" while not actually not making any progress, it's clearly not the thing you need to be focusing on.

Hold yourself accountable but realize that fuck ups are just there to help you re-calibrate your compass.
*** Improve Your "Stuff"
Keep your surroundings clean to a level you are truly satisfied with.

Temperately acquire things that you like, that inspire you and that make you comfortable but realize that barely anything you can buy is truly necessary.\\
Get rid of things that do nothing for you.

Recycle. Invest in Quality and Sustainability

Save money. Even if it's just a fraction of what you make. do it.
**** Have Beneficial Hobbies
Acquire hobbies that rejuvenate you. Doesn't matter what it is, if it replenishes your energy, good. If starts to drain, it's not a hobby, it's an addiction.

Also acquire hobbies that improve your skills. Learn a second language. Create. Read
*** Improve Your Fitness Level
Figure out what your specific goal is. Aesthetics? Functional Strength? Good Cardio? Raw Power? Mix of all?

Seek help in building a workout regime that lines up with what you want and what you actually do.

START SMALL, learn correct techniques.

Sore muscles are fine. Aching joints, stinging bones are not.
**** Lose/Gain Weight
LEARN TO COUNT CALORIES

Adopt eating habits that advance your goal, that you actually stick to. There could be the greatest, scientifically proven diet out there and it will do absolutely nothing for you if you aren't sticking to it.
**** Groom Yourself
Brush your teeth twice a day. Floss. Have regular dental exams.

Get a hairstyle that suits you and that you will actually maintain. Ask your barber.

Use deodorant but be careful about using too much scented products.

Find a skincare regime that works for you. If it ain't broke, don't fix it.
*** Improve Mental Health
**** Improve Social Skills
Stop thinking you NEED other people. This is not some edgy nihilism, just a way to healthy social interactions.

Welcome everyone without judgment

But stop desperate grasping for people because you think you "should" have friends or you "should" be in a relationship.

YOU HAVE ALL THE VALIDATION AND LOVE YOU NEED INSIDE YOURSELF

And truly realizing this will make you far more attractive than anything else

See yourself in everyone

Spend at least 5 minutes thinking about that sentence. Write it on paper and wrestle with it.
**** Improve Work
DON'T BE A WHINER. This doesn't mean never give constructive critique when given an opportunity, just don't be the guy always moaning about how hard something is. Nothing wrong with being dissatisfied either, just keep complaints out of the day-to-day professional setting.

Be dependable, not charitable. If something extra is within the scope of your duties, do it. Stay that much ahead of your work. If it's clearly you taking someone else's work, kindly refuse.\\
This can be very hard.

AVOID DRAMA. Don't gossip, don't talk shit about people.
# this part is relevant

Avoid bringing work home (bar homework).
* Allow things to pass
You will continue to suffer if you have an emotional reaction to everything is said to you.

True power is sitting back and observing things with logic. True power is restraint. If words control you that means everyone else can control you.

Breathe and allow things to pass.
* Confort is a drug
Once you get used to it, it becomes addicting.

Give a weak mean consistent sex, good food, cheap entertainment and he'll throw his ambitions right out the window.

*The comfort zone is where dreams go die*
# awesome phrase. i love it
* Do not try to change the world
#+begin_quote
Everyone things of changing the world, but no one things of changing himself.

-- Leo Tolstoy
#+end_quote
* Five Things Mentally Strong People Do
- They enjoy their time alone.
  They hold themselves accountable for their actions.
- They celebrate the success of others.
  They surround themselves with greatness.
- They have great health habits. From sleep to hot they eat, they own mind, body and spirit.
- They embrace and celebrate change.
  They know that change is constant with life.
- They invest time and energy into the present.
  They're able to focus on the tasks at hand.
* Great minds
*GREAT* people talk about *IDEAS*

*AVERAGE* people talk about *THINGS*

*SMALL* people talk about *OTHER PEOPLE*
* Growth and Fixed Mindset
** Growth Mindset
1. Embraces challenges
2. Persists in the face of setbacks
3. Sees effort as the path to mastery
4. Learns from criticism
5. Find lessons and inspiration in the success of others
** Fixed Mindset
1. Avoid challenges
2. Gets frustrated or gives up easily
3. Thinks potential is predetermined
4. Take criticism personally
5. Feels threatened by the success of others
* Inferior and Superior Man
#+begin_quote
The inferior man argues about his rights, while the superior man imposes duties on himself

Wagner Clemente Soto
#+end_quote
* Learn How To...
- Have fun without drinking
- Talk without mobile
- Dream without drugs
- Smile without selfies
- Love without conditions
* Lions don't roar
Lions don't have to roar. There is power in silence, confidence, and persistence.\\
Those who work don't talk, and those who talk don't work. Handle your business. Measure your efforts by results. Focus your time, energy, and activity on mastering and executing a plan.

*Avoid the energy draining practice of telling people what you're going to do.*
# crucial thing

Instead, spend your time and effort in doing the things that are necessary to accomplish your goals. Keep your focus. and stay determined in order to pursue your dream.

*Let your work, not your words, speak for itself.*

You deserve!
* Do Not associate With The Ignorant
#+begin_quote
If a wayfarer fails to find\\
one better or equal,\\
steadfast he should fare alone\\
for a fools no fellowship.
#+end_quote

Explanation: People need companions. But if one does not find a person who is better than, or at least equal to oneself, it is better to be alone rather than keep company with foolish people. There is no profitable companionship with fools.
* FAILURE
HOW TO OVERCOME THE FEAR OF IT.
1. Use it an opportunity to grow.
   "If you learn from defeat, you haven't really lost."
2. Figure out why you failed.
   "If you're not failing every now and again, it’s a sign you're not doing anything very innovative."
3. Failure is NOT FINAL.
   "Our greatest glory is not in never failing, but in rising every time we fail."
4. Stay Positive, It's all perspective.
   "I have not failed, I just found 10,000 ways that won't work."
* Spend on interior
#+begin_quote
Most people spend more on the exterior of their head than the interior.
#+end_quote
* Be consistent
SUCCESS DOESN'T COME FROM WHAT YOU DO OCCASIONALLY, BUT WHAT YOU CONSISTENTLY.
* You in 5 Years
#+begin_quote
The person you will be in five years depends largely on the books you read, the people you spend time with, the food you eat, the habits you adopt, and the conversations you engage in today.

Ruben Chavez
#+end_quote
* THE TWO SPIRITUAL CURRENCIES
There are two "Spiritual Currencies": *Time* and *Attention*.

This analogy can be seen very readily in the sayings "Spending Time" and "Paying Attention".

Whatever information or endeavors we put our time and attention toward, we end up getting something in return for that investment.

This return could come in the form of knowledge, understanding, skills, expertise, and empowerment, if we invest our Spiritual Currencies wisely.
* 29 ways to stay creative
1. Make lists
2. Carry a *notebook* everywhere
3. *Try free writing*
4. *Get away* from the computer
5. Quit beating *yourself* up
6. Take *breaks*
7. *Sing* in the shower
8. Drink *coffee*
9. *Listen* to new music
10. *Be open*
11. Surround yourself with *creative people*
12. Get *feedback*
13. *Collaborate*
14. *Don't give up*
15. Practice, *practice* and practice
16. Allow yourself to make *mistakes*
17. Go somewhere *new*
18. Count your *blessings*
19. Get lots of *rest*
20. Take *risks*
21. *BREAK THE RULES*
22. *Don't force it*
23. Read a page of *the dictionary*
24. Create a *framework*
25. Stop trying to be someone else's *perfect*
26. Got an *idea*? Write it down!
27. *Clean* your work place
28. *HAVE FUN*
29. *FINISH* something
* FRIENDS
#+begin_quote
You are the average of the *five people* you associate with most, so do not *underestimate* the effects of your pessimistic, unambitious, or disorganized friends. If someone isn't *making you stronger*, they're making you weaker.

-- Tim Ferriss
#+end_quote
* TO DO
- THINK POSITIVELY
- NETWORK WELL
- EXERCISE DAILY
- EAT HEALTHLY
- WORK HARD
- STAY STRONG
- BUILD FAITH
- WORRY LESS
- READ MORE
- BE HAPPY
- VOLUNTEER FREELY
- RELAX OFTEN
- LOVE ALWAYS
- LIVE FOREVER
* Educate yourself
When a question about a certain topic pops up, google it. Watch movies and documentaries. When something sparks your interest, read about it. Read read read. Study, learn stimulate your brain. Don't just rely on the school system, educate that beautiful mind of yours..
* Unhelpful thinking styles
** All or nothing thinking
Sometimes called "black and white thinking"

If I'm not perfect I have failed.

Either I do it right or not at all
** Mental filter
Only paying attention to certain types of evidence.

Noticing our failures but not seeking successes
** Jumping to conclusions
There's two key types of jumping to conclusions
- *Mind reading:* Imagining we know what others are thinking
- *Fortune telling:* Predicting the future
** Emotional reasoning
Assuming that because you feel a certain way what we think myst be true
#+begin_quote
I feel embarrassed so I must be an idiot
#+end_quote
** Labeling
Assigning labels to ourselves or other people
** Over-generalizing
Seeing a pater based upon a single event, or being overly broad in the conclusions we draw.
** Disqualifying the positive
Discounting the good things that happened or that you have done for some reason or another
#+begin_quote
That doesn't matter
#+end_quote
** Magnification (catastrophising) and Minimization
Blowing things out of proportion (catastrophising), or inappropriately shrinking something to make it seem less important.
** Should, must...
Using critical words like "should", "must" or "ought" can make us feel guilty, or like we already failed

If we apply "shoulds" to other people the result is often frustration.
** "This is my fault"
Blaming yourself or taking responsibility for something that wasn't your completely your fault

Conversely, blaming other people for something that was your fault.
* Why Only Few Succeed
- They know their *WHY*
- They value their *SLEEP*
- They live below *THEIR MEANS*
- They focus on *EDUCATION*
- They prioritize their *HEALTH*
* Why People Give Up
- Expect fast results
- Stop believing in themselves
- Get stuck in the past
- Dwell on mistakes
- Fear the future
- Resist change
- Give up their power
- Believe in their weakness
- Feel the world owes them something
- Fear failure more than desire success
- Never visualize what is possible
- Feel they have something to lose
- Overwork
- Assume their problems are unique
- See failure as the signal to turn back
- Feel sorry for themselves
# Sun Jan 21 07:42:55 2024
* VERDADES QUE VOCE NAO QUER LER
1. Você não alcança seus *OBJETIVOS* porque não tem disciplina.
2. Se suas metas não tem um *MÉTODO*, elas são apenas sonhos.
3. Ter um *PLANO B* nao vai te levar a lugar algum.
4. Se você esperar as condições perfeitas, *NUNCA* vai comecar.
5. Ideias não servem de *NADA* se não forem colocadas em prática.
6. A mudança que você quer está na *DECISAO* que você não toma.
* ENTENDENDO SUAS HABILIDADES
** Aprecie seu esforço.
Porque você está disposto a dar uma boa olhada em onde você já é forte e onde você pode melhorar, você já é uma pessoa forte. É preciso coragem para sentar e fazer esse trabalho. Dê um tapinha nas costas do seu eu incrível e lembre-se de que você é uma pessoa incrível.
** Anote o que você faz
Para identificar seus pontos fortes e fracos, pense nas atividades das quais você mais participa ou das quais tem mais prazer. Passe uma semana ou mais anotando todas as atividades que você faz ao longo de um determinado dia, classificando-as de um a cinco, dependendo do quanto você gosta de fazer ou participar delas.
** Reflita sobre seus valores
Às vezes, pode ser difícil identificar nossos pontos fortes e fracos porque não dedicamos tempo para esclarecer nossos valores fundamentais. Essas são as crenças que moldam como você pensa sobre si mesmo, os outros e o mundo ao seu redor. Eles são fundamentais para a sua forma de encarar a vida. Tirar algum tempo para identificar seus valores o ajudará a decidir se os aspectos de sua vida são pontos fortes ou fracos para você, independentemente do que os outros possam sentir sobre eles.
** Examine suas respostas para temas e padrões
Depois de refletir sobre seus valores, examine as respostas para coisas que podem se repetir. Por exemplo, talvez você admire Bill Gates e Richard Branson por seu espírito empreendedor e criatividade. Isso sugere que você pode valorizar Ambição, Competição e Ingenuidade. Talvez você mude a pobreza em sua comunidade para que todos tenham casa e comida. Isso sugere que você pode valorizar a Comunidade, Ajudando a Sociedade ou Fazendo a Diferença. Você pode ter vários valores fundamentais.
** Determine se sua vida se alinha com seus valores
Às vezes, podemos sentir que temos uma fraqueza em uma área específica quando nossas vidas não se alinham com nossos valores fundamentais, por qualquer motivo. Viver uma vida alinhada com seus valores é chamado de vida "congruente com os valores" e pode levar a maiores sentimentos de satisfação e sucesso.
** Considere os significados situacionais
Pense sobre o que constitui pontos fortes ou fracos em relação às convenções sociais ou costumes em seu contexto local. As convenções sociais são um conjunto de regras que governam a interação interpessoal que foram estabelecidas como funcionais dentro de uma determinada área geológica ou cultura, esperançosamente para ajudar a manter limites sociais saudáveis. Saber como eles diferem dependendo de onde você mora pode ajudá-lo a determinar o que pode ser visto como um ponto forte ou fraco nessa localização geográfica específica.
