#+title: The Most Hated Ally
#+filetags: awareness

Insecurities... We should love and take care of them. They're allies for our journey.

* Humility
Do you ever asked what in the children makes them learn so quick, improve so fast and grow so consistently in a short period of time?

Why after adolescence we start to degenerate and ignore important things?

I think it could be our ego, our arrogance growing and suffocating the humility.

And a reliable form to feed the humility, is with insecurities.


* Should I Fear?
Insecurities aren't fear.

You shouldn't fear.

Mistakes is a learning and should not be blamed, except if done intentionally.

The real failure is only when we stop trying.

So no, you can be fearless but also insecure.

Insecurity is more about understanding the largeness of things you don't know, it's about seeing where you really stand. Where you really are at.

It's highly tied with humility.


* Do Not Throw Them Away!
In the journey of life, the climb makes our past insecurities small and insignificant, and throwing them away feels a easy thing to do.

Since they make us feel bad in the present, we ask: Why bring it with us?

Unfortunately we're naturally ungrateful and it's normal to forget what helped us.

We forget that was it's its presence that brought us so high in the climb.

So then, we throw them away, and now we start to fall, slowly.

It's like placing a sun chair on the vertical-sloped mountain and relax.

On the best situation, you'll slowly slip down. In the worst, you'll die with the fall.

This is a ancient wisdom that books such Bible provide us. They talk about humidly, instruct to maintain awareness of our inabilities and weaknesses. They talk about this fall.

When we have no insecurities anymore, we start to walk blindly, and falling in every hole or trap.


* The "Good" News
But don't worry too much, insecurities are all around us.

And when you start to feel dangerously arrogant and prepotent, take the control back or you'll start to get blind.

Reflect on death, one of the greatest source of insecurities. The problem that humanity is incapable to solve. Never did and never will, but always tried.

Time is short. When you realize that, it will be too late.


* Outro
And keep in mind:
- *Everything* is not fine, there always something to improve.
- If you won't *do your best* in your present, you'll regret on your future.

Everyone has insecurities. Ones prefer to show, others tries to hide.

Just be cautious to not hide from yourself and get blind.
