#+title: The Most Hated Ally
#+filetags: awareness

#+begin_quote
| ~~

This is a random reflection highly based on my personal experiences, take with a grain of salt.
#+end_quote

Insecurities... We should love and take care of them. They're allies for our journey.

* Humility
Why do children learn and grow so quickly?

Why do we start to decline and ignore important things after adolescence?

Maybe is the ego growing and making our arrogance suffocate the humility.

Humility is somehow the courage to admit insecurities.


* Should I Fear?
Insecurity isn’t fear, but it's undeniable it can cause fear.

Fear blocks our mind, it's clear that we need to overcome the fears in life.

Makes no sense on fearing mistakes, they're an opportunity to learn and should not be blamed, except if done intentionally.

The real failure is only when we stop trying.

In this context and from my perspective, insecurity is about understanding the vastness of what you don't know, about seeing where you really stand, where you really are.


* So, Could I be a Jerk?
But it's also common for insecure people to be annoying and disrespectful.

Insecure people may try to take control of situations, constantly seek validation, or overstep boundaries in their interactions, dismiss alternative viewpoints, or become defensive and critical when challenged.

Insecurity can also lead to passive-aggressive behavior, envy, or attempts to undermine others in order to feel superior.

But this is an arrogant approach to handle insecurities. This is kinda an narcissism and it's poisonous to interpersonal relationships.

An healthy insecurity pushes you to improve and accept feedback.

Don’t compare your journey to others. You have your own time, just don't stop.

If you try to fake and hide your insecurities, everything gets worse, we're humans and we all know that.


* Do Not Throw Them Away!
In the journey of life, the climb makes our past insecurities small and insignificant, and throwing them away feels like an easy thing to do.

As they make us feel bad in the present, we ask: Why am I bringing this with me? Why not get rid of this discomfort?

Unfortunately we're naturally ungrateful and it's normal to forget what helped us.

We forget that it was its presence that brought us so high in the climb.

So then, we throw them away. But now we start to fall, slowly.

It's like placing a sun chair on a steep mountain slope and relaxing.

In the best case, you'll slowly slip down. In the worst, you'll die from the fall.

This is a teaching from ancient wisdom books such as the Bible.

One of the greatest personal values is humility.

These ancient wisdom books talk about it. Instruct us to maintain awareness of our inabilities and weaknesses, they premeditate this fall.

You can see that great downfalls have the same cause: arrogance and the blindness it brings.

In other words, *the lack of _prudence_.*

When we have no insecurities anymore, we start to walk blindly and fall into every hole or trap.


* The "Good" News
But don't worry too much, insecurities are all around us.

And when you start to feel dangerously arrogant and prepotent, take the control back or you'll start to get blind.

Reflect on death, one of the greatest sources of insecurity. A problem that humanity is incapable of solving. Never did and never will, but always tried.

Time is short. When you realize that, it will be too late.


* Outro
And keep in mind:
- *Everything* is not fine; there is always something to improve.
- If you don't *do your best* in the present, you'll regret it in the future.
- I'm not sure of what I'm talking about.

Everyone has insecurities. Some prefer to show it, others try to hide it.

Just be cautious not to hide from yourself and become blind. You don't have to show them, but if you fake, you will look a fool.
