#+title: The Most Hated Ally
#+filetags: awareness

#+begin_quote
| ~~

This is a random reflection highly based on my personal experiences, take with a grain of salt.
#+end_quote

Insecurities... We should love and take care of them. They're allies for our journey.

* Humility
Have you ever asked what it is in children that makes them learn so quickly, improve so fast, and grow so consistently in a short period of time?

Why do we start to decline and ignore important things after adolescence?

I think it could be our ego, our arrogance growing and suffocating the humility.

And a reliable form to feed the humility, is with insecurities.


* Should I Fear?
Insecurities aren't fear. They indeed bring fear, but it can be handled.

*You shouldn't fear.*

Mistakes are a learning opportunity and should not be blamed, except if done intentionally.

The real failure is only when we stop trying.

In this context and from my perspective, insecurity is more about understanding the vastness of what you don't know; it's about seeing where you really stand, where you really are.

It's closely tied to humility, from this perspective.


* So, Could I be a Jerk?
It's common for insecure people to be annoying and disrespectful.

Insecure people may try to take control of situations, constantly seek validation, or overstep boundaries in their interactions, dismiss alternative viewpoints, or become defensive and critical when challenged.

Insecurity can also lead to passive-aggressive behavior, envy, or attempts to undermine others in order to feel superior.

I think the right way to keep insecurities in control, yet not annihilate them, is to use them as motivation to improve, to keep you thirsty.

But never compare your journey with others'. You have your own time, and the key is not to stop.

Applying insecurity well makes you unsure if you did your best, making you improve and stay open to feedback.

Indeed narcissistic behavior relies on insecurities, but it's an arrogant way to handle them. Its the opposite of humility.

A humble person does not try to fake his insecurities.

The more you try to hide, the bigger the problem becomes.


* Do Not Throw Them Away!
In the journey of life, the climb makes our past insecurities small and insignificant, and throwing them away feels like an easy thing to do.

As they make us feel bad in the present, we ask: Why am I bringing this with me? Why not get rid of this discomfort?

Unfortunately we're naturally ungrateful and it's normal to forget what helped us.

We forget that it was its presence that brought us so high in the climb.

So then, we throw them away. But now we start to fall, slowly.

It's like placing a sun chair on a steep mountain slope and relaxing.

In the best case, you'll slowly slip down. In the worst, you'll die from the fall.

This is a teaching from ancient wisdom books such as the Bible.

One of the greatest personal values is humility.

These ancient wisdom books talk about it. Instruct us to maintain awareness of our inabilities and weaknesses, they premeditate this fall.

You can see that great downfalls have the same cause: arrogance and the blindness it brings.

In other words, *the lack of _prudence_.*

When we have no insecurities anymore, we start to walk blindly and fall into every hole or trap.


* The "Good" News
But don't worry too much, insecurities are all around us.

And when you start to feel dangerously arrogant and prepotent, take the control back or you'll start to get blind.

Reflect on death, one of the greatest sources of insecurity. A problem that humanity is incapable of solving. Never did and never will, but always tried.

Time is short. When you realize that, it will be too late.


* Outro
And keep in mind:
- *Everything* is not fine; there is always something to improve.
- If you don't *do your best* in the present, you'll regret it in the future.
- I'm not sure of what I'm talking about.

Everyone has insecurities. Some prefer to show it, others try to hide it.

Just be cautious not to hide from yourself and become blind.
