#+title: Effects Of Demonizing Things
#+filetags: draft

* Organizing the Thoughts :noexport:
This is the first post of this blog. I'm excited.

I'll try a new method: Free-form writing in a non-exported section to organize the ideas and then refactor below in a cleaner version, reviewed and evaluated.

Let's start by re-writing my initial thoughts.

-----

The seed of this inspiration was the following thought:
#+begin_quote
Saying something's bad doesn't make people avoid it. It makes you avoid the people who do that. Induces polarization.
#+end_quote

This thought came when thinking on witches and Christianism, while hearing the book "Women Who Run with the Wolves". Specifically, trying to understand the reason behind it's demonization.


I developed this thought a little before coming here to write, so now I have some thesis I want to defend:
- Your discernment of good and bad is useful only to yourself and to the people who hears you.
  + It doesn't justify you to enforce for anyone that doesn't wants to hear you.
- The discernment is by itself shows you who is your ally and who is not.
  + Write what's an ally and what's an enemy.
- Demonizing something is not useful to reduce the practice of that thing.
  + Reflect on what could be the intention of Christianism on demonizing things like witches.
  + In the case of witches, isn't probable that their intention was reduce the witchcraft. Since prohibition and fear-based decision making doesn't lasts.
    + What's the consequences?
      - Witchcraft becomes a secret practice.
      - Hate between groups.
      - Great environment for conspiracies between each others.
      - Knowledge becomes restricted.
        + This is how atheism see the "religion".
        + Enforced restrictions and rules towards external people generate strong decisions on them: Agreement or rebellion.
      -


I also want to talk about the items below, but I won’t (for now) because I haven't enough study about these topics.
- I know the origins of demonization of witches don't come from Christianism era, but very earlier.
