on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  gh-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install nim

        id: install_nim
        uses: iffy/install-nim@v3

      - name: install library dependencies
        run: nimble install -y

      - name: install libsass
        run: sudo apt install libsass-dev

      - name: build run_all_release
        run: nimble run_all_release

      - name: deploy on github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          cname: blog.thisago.com
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
